import Header from "@/components/header/page";
import "./globals.css";
import { Inter } from "next/font/google";
import layoutCss from "./layout.module.css";

import Footer from "@/components/footer/page";
const inter = Inter({ subsets: ["latin"] });
export const metadata = {
  title: "Home",
  description: "Generated by create next app",
};
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className={layoutCss.Container}>
          <Header />
          <div>{children}</div>
          <Footer />
        </div>
      </body>
    </html>
  );
}
